### PR TITLE
Make Status: signs display multi-flyblock counts

### LINKED ISSUE #354: Status signs are no longer functional
**Describe the bug**
When adding a flyblock that can be comprised of multiple blocks for example [5, 125, 126] (wood, wooden slabs and wooden double slabs) only the first flyblock in the list is taken into account when calculating it on the status sign.

**To Reproduce**
1. Make craft with a flyblock that has multiple IDs.
2. Pilot that craft and update the status sign.

**Expected behavior**
All block IDs in the list should be counted into the status sign, just like in the sinking calculation.

**Versions (please complete the following information):**
 - Movecraft 7.0 beta 7
 - Java 1.8.0_271
 - Minecraft/Paper 1.12.2

### PR DESCRIPTION
**Pull request by HumorousFool**
### Describe in detail what your pull request acomplishes
This PR makes it so that all blocks in multi-flyblocks are taken into account on Status: signs.

### Related issues:
- fix #354 

### Checklist
- [x] Proper internationalization
- [x] Compiled/tested

### CODE REVIEW

**Review by TylerS1066 — CHANGES_REQUESTED** [review]
Has this been tested?  From a cursory reading it would appear that it may have problems with a large number of fly blocks extending past the limit on the number of characters on a sign, crashing either the server or clients (or something odd).

**Comment by HumorousFool** [comment]
It has but not in the situation you describe, I will test again

**Comment by TylerS1066** [comment]
Something else I thought up, it would be nice to include moveBlocks in the status sign if there is space.

**Comment by TylerS1066** [comment]
After extensive testing and realizing how laggy Status: signs are, I'd like to hear @cccm5 's input before going forward with this.

**Comment by HumorousFool** [comment]
Considering ccm's flyblock counting improvements, this should be rewritten

**Pull request closed without merging**
