### PR TITLE
Benchmarking

### PR DESCRIPTION
**Pull request by keough99**
added benchmarking to get a performance status and to hopefully improve performance of movecraft

### CODE REVIEW

**Comment by cccm5** [comment]
What does this do that can't be accomplished by pre-existing software on a system? Also opening any sort of executable from a plugin is pretty much a no go for publishing spigot.

**Comment by keough99** [comment]
allowing benchmarking within the plugin would help for seeing the performance of the plugin and would help users find out how much ram and such the plugin takes up without having to add or download other types of software. the opening of the executable can be replaced

**Comment by cccm5** [comment]
Again though, any server owner should be able to determine how much memory they have dedicated to there own server.

**Comment by Pulverizer** [comment]
@cccm5 I think he means it checks the plugin's usage not the server's usage. Basically, how much of the server's usage is caused by movecraft?
@keough99 am I right?

**Comment by keough99** [comment]
Yes but it also says the usage and can help with debugging, so let's say someone moves a Goliath sized ship and they want to figure out how much more ram is needed or how much resources is being used when moving a Goliath sized ship. This would also help if someone is using a minecraft hosting company and the control panel doesn't display the usage they would be able to use the benchmark tool to look at the resource useage

**Comment by cccm5** [comment]
What he has submitted only shows the servers memory usage. It does nothing to profile movecraft in any way

**Pull request closed without merging**
