### PR TITLE
Add 1.19 support

### PR DESCRIPTION
**Pull request by galacticwarrior9**
### Describe in detail what your pull request accomplishes

This PR adds support for 1.19 to Movecraft. It appears to compile and build, but cannot be tested until ProtocolLib updates to 1.19.

### Checklist
- [x] Proper internationalization
- [x] Tested

### CODE REVIEW

**Comment by TylerS1066** [comment]
> namely the Spawn Living Entity packet, but substituting this with the Spawn Entity packet seems to [work](https://github.com/CCNetMC/Movecraft/commit/e64da83ed308ea977a30f4e41a78b161780811b1)

Can you implement this change on this branch?

> or have had their structure changed (`PacketPlayOutEntityDestroy`).

Is it possible to make the code work with both without reflection?

**Review by TylerS1066 — CHANGES_REQUESTED** [review]
1.19 no longer includes `#carpets` as a tag, it's been replaced with `#wool_carpets`.

I'm not sure the best way to address this, but I think the best might be to create a movecraft tag for `#wool_carpets` that replicates the new vanilla behavior of 1.19 and update the craft files to use it.

**Comment by galacticwarrior9** [comment]
> > namely the Spawn Living Entity packet, but substituting this with the Spawn Entity packet seems to [work](https://github.com/CCNetMC/Movecraft/commit/e64da83ed308ea977a30f4e41a78b161780811b1)
> 
> Can you implement this change on this branch?
> 
> > or have had their structure changed (`PacketPlayOutEntityDestroy`).
> 
> Is it possible to make the code work with both without reflection?

Will do. As for the second issue, I'm not too sure how to best deal with that code. On my branch, I replaced some ProtocolLib usage with [PacketEvents](https://github.com/retrooper/packetevents/tree/2.0), which I think is easier to support multiple versions with. However, I was only able to do this for some of the code and I'm not sure whether that's an approach you would like to take on this branch (there's probably an easier way I'm missing)

**Comment by TylerS1066** [comment]
> Will do. As for the second issue, I'm not too sure how to best deal with that code. On my branch, I replaced some ProtocolLib usage with [PacketEvents](https://github.com/retrooper/packetevents/tree/2.0), which I think is easier to support multiple versions with. However, I was only able to do this for some of the code and I'm not sure whether that's an approach you would like to take on this branch (there's probably an easier way I'm missing)

I think for now it'd be best to keep the functionality as is (as best we can) and merely disable the feature on 1.19.  Does that seem possible?

**Review by TylerS1066 — APPROVED** [review]

**Pull request merged**
