### PR TITLE
UI/HUD features

### LINKED ISSUE #137: Bossbar for siege
**Is your feature request related to a problem? Please describe.**
I'm annoyed that eirik gets to add bossbar to repairs.

**Describe the solution you'd like**
I'd like to add bossbars to siege!

### PR DESCRIPTION
**Pull request by drfiveminusmint**
### Describe in detail what your pull request acomplishes
Added bossbars for siege and assault timers, as well as for assault damage. Added a manoverboard timer on a sidebar display. Additionally, created a new class MovecraftUIManager to facilitate future UI/ HUD features.

### Related issues:
- This will fix #137
- Not technically an issue, but a manoverboard timer display was requested by users in AP Admin discord.

### Checklist
- [X] Unit tests 
- [X] Proper internationalization
- [X] Compiled/tested

### CODE REVIEW

**Comment by cccm5** [comment]
This is fairly over complicated for what is needed - there's no reason to make a task for updating boss bars, nor a manager class for it.

**Comment by drfiveminusmint** [comment]
The manager class isn't just for boss bars, it also controls the scoreboard. The reason for the BossBarUpdateTask is that the SiegeProgressTask (which I previously used for the siege boss bar) runs infrequently (every 10 minutes by default), resulting in very choppy movement of the boss bar and somewhat negating its purpose (as the bar won't move at all for the last 10 minutes/ whatever it is configured as).
I will admit that assaults could be done without using the BossBarUpdateTask (as the task for assaults runs far more frequently, either every tick or every second, I forget which) but I prefer to use the same system as sieges for consistency. If there's an easier or preferred way to do this let me know.

**Comment by drfiveminusmint** [comment]
@cccm5 what things would you like me to delete/change/add?

**Comment by cccm5** [comment]
I'm trying to avoid adding UI features unless they're explicitly necessary, I'm going to hold of on these types of features until after the initial release.

**Comment by FrozenBeard** [comment]
Tell you a UI feature we do need, is color on signs once they are active, like when you pilot the ship, turn its text blue on the sign and add piloted under it.

**Pull request closed without merging**
