### PR TITLE
1.20.2

### PR DESCRIPTION
**Pull request by TylerS1066**
### Describe in detail what your pull request accomplishes
This PR replaces 1.20.1 support with 1.20.2.

### Checklist
- [x] Tested

### CODE REVIEW

**Comment by TylerS1066** [comment]
Tested with a local build on latest Spigot (`3922-Spigot-dba3cdc-75502b6`) and Purpur (`1.20.2-2082`).  Paper download server is down but *should* work.  Not sure why the CI is failing.

**Comment by TylerS1066** [comment]
CI works, latest Paper (`1.20.2-241`) works as well.

**Comment by Xyaren** [comment]
When can we expect a release for this ?

**Comment by TylerS1066** [comment]
There hasn't been enough development since this to warrant a new release.  As recommended in our discord, you can always go to the Actions tab and download a dev build if you need the latest Minecraft version support.

**Pull request merged**
